-----------------------------------------------------CASE STUDY 1 --------------------------------------------------
create database Casestudy1

use Casestudy1

---Improting flat file done by GUI method -------------

-- All three file below ------------------
select * from fact

select * from Location

select * from Product

--Q1: Display the number of states present in the Location Table
select count(distinct state)as Total_States from Location

--Q2: How many product are of regular type in Product Table
select count(Type) as Total_Regular_type  from product where type = 'regular' 

--Q3: How much Total spending has been done on marketing of product ID 1 in Fact table ?
select sum(Marketing)as Total_Marketing_exp from fact where ProductId=1

--Q4: What is the minimun sales of a products in Fact tabel?
select min(sales)as Min_sales from fact

--Q5: Display the max Cost of Good Sold (COGS) in Fact table?
select max(COGS) as Max_COGS from fact 

--Q6: Display the details of the product where product type is coffee in Product table?
select * from product where product_type ='Coffee'

--Q7: Display the details where total expenses are gerater than 40 in Fact table?
select * from fact where total_Expenses > 40  order by Total_Expenses desc

--Q8: What is the average sales in area code 719 in fact table?
select avg(sales)as Avg_Sales from fact where area_code=719

--Q9: Find out the total profit generated by colorado state from loaction and fact table?
select sum(profit)as Total_profit from fact as F inner join location as L on 
F.Area_Code = L.Area_Code group by state having state='colorado'

--Q10: Display the average inventroy for each product ID in fact table?
select productid ,avg(Inventory)as Avg_Inven from fact group by productid order by productid

--Q11: Display state in a sequential order in a location table?
select distinct state from location order by state

--Q12 : skiped bue to wrong question

--Q13: What is the total sales done on date 2010-01-01 in Fact table?
select sum(sales)as Total_Sales from fact where date='2010-01-01'

--Q14: Display the average total expense of each product ID on an individual date from fact table.
select date ,Productid , avg(total_expenses)as Avg_total_exp from fact group by 
Productid,Date order by Productid

--Q15: Display the table with the following attributes such as date, productID, product_type,
-- ,sales , profit , state , area_code  from Fact, Location  and product table

select date ,p.productID, product_type, sales ,profit , state , f.area_code 
from fact as f join location as l on
f.area_code = l.area_code join product as p on p.productid = f.ProductId

--Q16: Display the rank without any gap to show the sales wise rank from fact teble

select sales ,dense_rank() over ( order by  sales desc) as Sales_Ranking from fact 

--Q17: Find the state wise profit and sales from fact and location table

select state , sum(sales) as State_Sales, sum(profit) as State_profit  from fact 
as f inner join location as l on f.Area_Code = l.Area_Code group by state

--Q18: Find the state wise profit and sales along with the productname from fact , location , product table

select l.State, p.Product , sum(f.Profit) as State_Profit , sum(f.sales) as State_Sales from 
fact as f inner join location as l on f.Area_Code = l.Area_Code inner join product as p on 
p.ProductId = f.ProductId group by state,product order by state, product

--Q19: If there is an increase in sales of 5%, calculate the increasedsales.

select Sales , Sales * 1.05 as Incrased_sales from fact order by sales desc 

--Q20: Find the maximum profit along with the product ID and producttype.

select f.ProductId , p.Product_Type , f.profit from product p join
fact f on p.productId=f.productId 
where f.profit = ( select max(profit) from fact)

--Q21: Create a stored procedure to fetch the result according to the product type from ProductTable.

create procedure fetch_data
    @Product_type varchar(255)
as
begin
select * from product where product_type = @product_type
end

exec fetch_data 'espresso'

--Q22: Write a query by creating a condition in which if the total expenses is less than
--     60 then it is a profit or else loss.

select Total_Expenses, iif(Total_Expenses < 60 , 'Profit','Loss')as Profit_or_Loss from fact 

--Q23: Give the total weekly sales value with the date and productID details. Use
--     roll-up to pull the data in hierarchical order.

select datepart(week,date) as week_no, date , ProductId ,
sum(sales) as total_sales from fact 
group by datepart(week , date), date, productid with rollup

--Q24: Apply union and intersection operator on the tables which consist of attribute area code.

select Area_Code from fact 
union
select Area_Code from location

select Area_code from fact
intersect
select area_code from location

--Q25: Create a user-defined function for the product table to fetch a particular
--      product type based upon the user’s preference.

create function getpro(@type varchar(255))
returns table 
as 
return 
(
    select * from product where product_type = @type
)

select * from getpro('Tea')


--Q26: Change the product type from coffee to tea where product ID is 1 and undo it.
begin transaction
update product set product_type ='Tea' where productid = 1

rollback


--Q27: Display the date, product ID and sales where total expenses are
---    between 100 to 200.

select date, productid, sales, total_expenses  from fact where 
total_expenses between 100 and 200;

--Q28: Delete the records in the Product Table for regulartype.
delete from product where Type = 'regular'

--Q29: Display the ASCII value of the fifth character from the column Product.

select ascii(substring(product_type,5,1)) as ASCII_value from product


